FROM node:9.10.1

# The base node image sets a very verbose log level.
ENV NPM_CONFIG_LOGLEVEL warn

RUN apt-get update && apt-get install -y \
  git-core   

# Copy all local files into the image.
RUN git clone https://github.com/CriMenghini/daf-monitopa.git

WORKDIR /daf-monitopa/web-ui

RUN git checkout production

RUN npm install

# Build for production.
RUN npm run build --production

# Install `serve` to run the application.
RUN npm install -g serve

# Set the command to start the node server.
CMD serve -l 3000 -s build

# Tell Docker about the port we'll run on.
EXPOSE 3000
